### ISSUE TITLE
add ChargE3Net to leaderboard

### ISSUE THREAD

**Issue by nmz787-intel** [janosh/matbench-discovery#101]
https://github.com/AIforGreatGood/charge3net

**Comment by janosh** [comment]
new model submissions to Matbench Discovery are very welcome!
however from skimming the paper, ChargE3Net models electronic rather ionic structure, specifically charge density.
sounds like it's not a good fit for the Matbench Discovery task of predicting formation energies

**Comment by janosh** [comment]
closing as stale
