### ISSUE TITLE
How to calculate the MAE of the submitted files

### ISSUE THREAD

**Issue by lamthuy** [janosh/matbench-discovery#103]
Hi,
I am new to this benchmark. I am trying to figure out the correct way to calculate the MAE of my prediction. I am not sure the following steps are correct (sorry I could not find a documentation anywhere in the website):
To get the ground truth structure and the energy per atom, I need to download both files:

-  wbm_initial_structures where I can get the initial structure of all unrelaxed crystals, I saw another file wbm_computed_structure_entries bu not sure what is it for?
- wbm_summary, to get the ground truth energy per atom I look at the column e_correction_per_atom_mp2020

I took my prediction and calculated the MAE between my prediction and the given ground-truth energy above.

Could you please tell me is that the correct way to validate the MAE of my model?

Since I am not sure what is the correct way to do so, so I looked into https://github.com/janosh/matbench-discovery/tree/main/models/chgnet with some submitted prediction files. I downloaded one of them, for example, the [2023-12-21-chgnet-0.3.0-wbm-IS2RE.csv.gz](https://github.com/janosh/matbench-discovery/blob/main/models/chgnet/2023-12-21-chgnet-0.3.0-wbm-IS2RE.csv.gz). That file has three columns:

```
material_id,chgnet_energy,e_form_per_atom_chgnet
wbm-1-1,-42.8388,0.5589
wbm-1-2,-25.9892,0.0934
wbm-1-3,-35.0625,0.7332
wbm-1-4,-9.1859,0.0142
wbm-1-5,-13.3448,-0.2062
wbm-1-6,-16.3522,-0.2686
wbm-1-7,-8.398,-0.2713
wbm-1-8,-16.8369,-0.2781
wbm-1-9,-15.2442,-0.4043
```
Which column is actual prediction?

**Comment by lamthuy** [comment]
I double checked again it more likely that the ground truth is the e_form_per_atom_mp2020_corrected from the wbm_summary file because when I calculate the MAE between  the e_form_per_atom_chgnet and the  e_form_per_atom_mp2020_corrected it is approximately 0.06 which is the reported MAE of chgnet.
This makes me more confused because according  to https://figshare.com/articles/dataset/Materials_Project_Trjectory_MPtrj_Dataset/23713842 chgnet was trained on : 

-'energy_per_atom': [eV/atom] corrected energy per atom, this is the energy label used to train CHGNet

rather than:

-'ef_per_atom': [eV/atom] formation energy per atom ?

**Comment by CompRhys** [comment]
1. In chgnet file both the numerical columns "chgnet_energy" and "e_form_per_atom_chgnet" come from predictions of the model. The first is the total energy of the structure as predicted by CHGNet and the second is the formulation energy per atom that is calculated from that prediction and the MP reference state energies. CHGNet was trained on the corrected energies and so there is no need to apply the post-hoc MP compatibility settings.
2. "e_form_per_atom_mp2020_corrected" is the correct target to compare corrected energy predictions against. https://github.com/janosh/matbench-discovery/blob/9a4fe69ffc8395e0e48dcce73450d3120d7d5117/matbench_discovery/enums.py#L51 provides a key to various labels used. There's quite a lot of careful logic that goes into making sure that we get the right numbers when people use different corrections etc and so our preference is for people to just submit predictions and allow us to generate the results using the code in this repo but we can perhaps think about how to document it slightly more clearly to enable more extensible usecases.

**Comment by lamthuy** [comment]
Thank you for the explanation, regarding " the second is the formulation energy per atom that is calculated from that prediction and the MP reference state energies", is there MP reference state energies for the WBM test structures available? If it is not available for the test structures, is it available for a validation structure?

**Comment by janosh** [comment]
> is there MP reference state energies for the WBM test structures available

yes, have a look at the `e_form_per_atom_mp2020_corrected` column in `matbench_discovery.data.df_wbm`.

i'll go ahead and close this issue. feel free to use the [discussion tab](https://github.com/janosh/matbench-discovery/discussions) for future questions. the issue tracker is mostly for bugs and features
