### ISSUE TITLE
Are non-python-based models allowed

### ISSUE THREAD

**Issue by lprekon** [janosh/matbench-discovery#108]
I've been doing some work in Rust that I'm interested in testing here. Can we submit test and training code that's not python?

It would be quite easy to wrap the environment setup and execution in a python script so it's still python at the top level, but would require non-python dependencies. Is that acceptable?

**Comment by janosh** [comment]
absolutely, that's acceptable. let me know if you encounter any blocker in the model submission process from not using Python. i'm happy to make changes to accommodate other languages, esp. rust. no strict requirement to wrap your model in a Python script either. though other users might appreciate that and so worth considering i think.

**Comment by janosh** [comment]
closing as non-actionable for now. feel free to revive this thread if any hurdles arise.
