### ISSUE TITLE
Improper sorting on "Model Params"

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [janosh/matbench-discovery#124]
Sorting by model parameters doesn't sort correctly due to improper accounting for K vs. M.

![image](https://github.com/user-attachments/assets/ef298387-af7a-4cf1-83e0-a388518e0f0b)

**Comment by janosh** [comment]
thanks for reporting! noticed that as well but neglected to open an issue for it.

just for later reference, needs to be fixed here [`svelte-zoo/src/lib/actions.ts`](https://github.com/janosh/svelte-zoo/blob/f8457d5464ee8d55f5d962f17b3b6fc356bd7e03/src/lib/actions.ts#L1).
started working on a fix last month in https://github.com/janosh/elementari/pull/50 to turn numeric strings with metric suffixes back into floats, then thought might be smarter to save the unformatted value into HTML `data` attributes on each table cell and preferentially sort by that if found. unfortunately, other stuff got in the way of implementing that.
