### ISSUE TITLE
Unpinned Pymatviz causes backward incompatability issues

### ISSUE THREAD

**Issue by DeNeutoy** [janosh/matbench-discovery#145]
We are running a specific pinned version of matbench, but the new release of pymatviz is breaking our install. Perhaps pymatviz should be pinned to a certain version if it will have breaking changes - this would prevent this happening again in the future.

```sh
git clone https://github.com/janosh/matbench-discovery.git
cd matbench-discovery
git checkout 5c8601a
pip install -e .
```

Then, when running:

```py
"Traceback (most recent call last):
  File "/work/orb/libs/core/scripts/matbench/matbench_eval.py", line 16, in <module>
    from matbench_discovery import today
  File "/work/orb/libs/core/matbench-discovery/matbench_discovery/__init__.py", line 14, in <module>
    from matbench_discovery.enums import MbdKey, Model, Quantity
  File "/work/orb/libs/core/matbench-discovery/matbench_discovery/enums.py", line 6, in <module>
    from pymatviz.utils import styled_html_tag
ImportError: cannot import name 'styled_html_tag' from 'pymatviz.utils' (/usr/local/lib/python3.11/dist-packages/pymatviz/utils.py)"
```

**Comment by janosh** [comment]
can you `pip show pymatviz` and post your version here? i think 0.11 and 0.12 pypi releases should not have this problem and 0.11 is the oldest allowed version

**Comment by DeNeutoy** [comment]
Right - that requirement is for the latest release of matbench, but the issue is that if I install e.g `matbench-discovery==1.2.0`

it will use the corresponding tag and pyproject.toml:

https://github.com/janosh/matbench-discovery/blob/v1.2.0/pyproject.toml

where pymatviz does not have an upper bound dependency, and hence breaks.

**Comment by janosh** [comment]
got it. is there anything preventing you from changing to `matbench-discovery==1.3.1`?

**Comment by DeNeutoy** [comment]
https://github.com/janosh/matbench-discovery/pull/114

This PR broke all the scripts I had written for the original evaluation, and I didn't want to upgrade it at the time - I will try to upgrade now.

**Comment by janosh** [comment]
i see. should be straightforward migration. rename from `CONSTANT_CASE` to `PascalCase`, then append `.path` to any attribute access, e.g.  `DATA_FILES.wbm_summary -> DataFiles.wbm_summary.path` or `str(DataFiles.wbm_summary)` if you just want the file path but don't want to trigger an auto-download if the file isn't already cached locally

**Comment by janosh** [comment]
closing this as assumed resolved
