### ISSUE TITLE
Key.daf.symbol: AttributeError: 'Key' object has no attribute 'symbol'

### ISSUE THREAD

**Issue by pbenner** [janosh/matbench-discovery#174]
https://github.com/janosh/matbench-discovery/blob/85f65b6139fd4726d911fe18dc0b3718e5cb2781/matbench_discovery/preds/discovery.py#L59

    df_metrics_uniq_protos.loc[Key.daf.symbol, model_name] = (
                               ^^^^^^^^^^^^^^
AttributeError: 'Key' object has no attribute 'symbol'

> pip list | grep pymatviz
pymatviz                 0.14.0

**Comment by janosh** [comment]
sorry for the inconvenience. i'm changing a lot over at [`pymatviz`](https://github.com/janosh/pymatviz) so i started installing the `main` branch in the MBD CI to avoid the need for constant PyPI releases. if you `pip install git+https://github.com/janosh/pymatviz` locally, that should always work with the MBD `main`

**Comment by janosh** [comment]
should be fixed by [`pymatviz==0.15.0`](https://github.com/janosh/pymatviz/releases/tag/v0.15.0)
