### ISSUE TITLE
Does figshare url for `wbm_summary` change?

### ISSUE THREAD

**Issue by lan496** [janosh/matbench-discovery#177]
Hi, thank you for the awesome package for benchmarking universal NNPs!

The current url for `wbm_summary` (https://figshare.com/ndownloader/files/40344472) returns "EntityNotFound" error.
https://github.com/janosh/matbench-discovery/blob/41ccd263b44adf4eb4f4b290a0b3d932fc50e90d/matbench_discovery/data-files.yml#L69

Before merging https://github.com/janosh/matbench-discovery/pull/161/files, it pointed to other url "https://figshare.com/ndownloader/files/44225498".
Does it change?

**Comment by lan496** [comment]
@janosh Sorry for pinging you, but are the figshare URLs recently reorganized?

**Comment by CompRhys** [comment]
Thanks for pointing this out!

https://figshare.com/articles/dataset/Matbench_Discovery_v1_0_0/22715158?file=44225498 I believe that this link should return the correct file (same id as old link). 

I believe this is indeed a mistake introduced in the refactor, we should update our tests to check the links don't give such errors.

**Comment by janosh** [comment]
@lan496 thanks for catching and reporting this! should be fixed and future regressions prevented by the new `test_data_files_urls` added in https://github.com/janosh/matbench-discovery/commit/f3ad7e5879b159a91fda2e33a13574c9b98ba289
