### ISSUE TITLE
Questions about newly updated mattersim-v1

### ISSUE THREAD

**Issue by YutackPark** [janosh/matbench-discovery#184]
Firstly, thanks for maintaining the leaderboard. I'm receiving news from matbench quite a lot.

As mattersim has changed its model to M3GNet, which uses force prediction using energy grad, I wondered whether it keep using direct force prediction, and I found this:

https://github.com/microsoft/mattersim/blob/main/src%2Fmattersim%2Fforcefield%2Fpotential.py#L749-L750

Maybe update on the target column is omitted, or I'm misunderstanding something. (+ unlike original mattersim, mattersim-v1 seems open source open data)

**Comment by janosh** [comment]
thanks for pointing this out! leaving MatterSim v1 `targets` as `EFS_D` was an oversight. should be `EFS_G` now. likewise for `openness: CSCD -> OSCD`. note that MatterSim v1 is now open source (OS) but still closed data (CD). @samblau asked @txie-93 about releasing the MatterSim dataset at MRS Boston. didn't sound like there are imminent plans
