### ISSUE TITLE
Cannot import `matbench_discovery.data` in normal package installation

### ISSUE THREAD

**Issue by lan496** [janosh/matbench-discovery#185]
The following error occurs when I try to import `matbench_discovery.data` with normal installation (`pip install .`). 

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/matbench_discovery/data.py", line 507, in <module>
    px.defaults.labels |= {k: v.label for k, v in Model.member_map.items()}
                              ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/matbench_discovery/data.py", line 449, in label
    return self.metadata["model_name"]
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/matbench_discovery/data.py", line 438, in metadata
    with open(yaml_path) as file:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.12/dist-packages/matbench_discovery/models/alignn/alignn.yml'
```

I think this comes from the following line, which always tries to search `models` directory. Is there any workaround?
 
https://github.com/janosh/matbench-discovery/blob/fa0d56ecae99a49fb498646297381e78d6a1a71d/matbench_discovery/data.py#L507

**Comment by janosh** [comment]
thanks for reporting. noticed the same problem recently. can you try again with the changes in a937a1a? i think it might help even if it's not a clean solution as it creates a `models/` folder in the root directory of `site-packages/` when using non-editable `pip install .`

**Comment by lan496** [comment]
Thank you for the prompt fix. It worked!
