### ISSUE TITLE
Package uses non-standard site-package paths for resources

### ISSUE THREAD

**Issue by pbenner** [janosh/matbench-discovery#25]
The package seems to use the following non-standard paths:
```
[...]/site-packages/tmp
[...]/site-packages/data
```
Please use *pkg_resources* for determining package resource paths.

**Comment by janosh** [comment]
`pkg_resources` [is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html). Maybe we should use [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources). I'll have to read up on that.

**Comment by janosh** [comment]
@pbenner are the `/tmp` and `/data` directories empty or actually used for anything. maybe the solution is just to get rid of this or check if the package is using an editable install before running this.

https://github.com/janosh/matbench-discovery/blob/1098aa616ebe3f2e8763bd66a04fc1abdf003962/matbench_discovery/__init__.py#L20-L23

**Comment by pbenner** [comment]
The *[...]/site-packages/data* directory is created when installing the package and it contains the figshare files, because of:
https://github.com/janosh/matbench-discovery/blob/13cbb90b1e05d2122d4633cb6bf9706b9e83babf/pyproject.toml#L76

One solution would be to move the *data/figshare* folder into the *matbench_discovery* folder. But I guess it would take a few more modifications to turn it into a real python package. For instance, this is not compatible:
https://github.com/janosh/matbench-discovery/blob/13cbb90b1e05d2122d4633cb6bf9706b9e83babf/matbench_discovery/__init__.py#L13-L19
The *ROOT* variable points to the *[...]/site-package* directory.

**Comment by janosh** [comment]
@pbenner Sorry this took ages to address. I think I fixed the supporting data directories being created in root-level `/site-packages` in 55ab66b. This dynamic way of deciding where data files go feels like a bad solution:

https://github.com/janosh/matbench-discovery/blob/55ab66b409c2849ce98dd1833d847b034d157451/matbench_discovery/__init__.py#L15-L20

I opened https://github.com/pypa/setuptools/issues/4186 to either design a less hacky way of implementing this or maybe learn how to better address the underlying issue.
