### ISSUE TITLE
Reference: Critical examination of robustness and generalizability

### ISSUE THREAD

**Issue by pbenner** [janosh/matbench-discovery#41]
Maybe another reference for the paper to motivate this work:

Li, Kangming, et al. [A critical examination of robustness and generalizability of machine learning prediction of materials properties](https://arxiv.org/abs/2210.13597). npj Computational Materials 9.1 (2023): 55.

**Comment by janosh** [comment]
@pbenner Thanks for the pointer! This work definitely fits the bill.

Might be worth it to repro the UMAP projections in figs 6. and 8. for the WBM test set. Also, fig. 5 right panel is very relevant given the observed [spacegroup 71 failure case of Wrenformer](https://matbench-discovery.materialsproject.org/si#spacegroup-prevalence-in-wrenformer-failure-cases).

**Comment by CompRhys** [comment]
added to bibtex in preprint

**Comment by janosh** [comment]
@CompRhys Was already in `references.bib` as `li_critical_2023`.
