### ISSUE TITLE
Importing CSV with pd.read_json()

### ISSUE THREAD

**Issue by pbenner** [janosh/matbench-discovery#43]
The file format of `DATA_FILES.mp_energies` is now CSV:

https://github.com/janosh/matbench-discovery/blob/4a90dee85965aebbcfcd547353c548eeb19651ce/models/cgcnn/train_cgcnn.py#L65

Also, the `structure` column was removed, which is required for training.

**Comment by janosh** [comment]
Great catch! I found 3 more places with similar problems.  Hopefully didn't miss any.

Might have been smarter to store everything as JSON (at the cost of ~50% larger files).

**Comment by pbenner** [comment]
Thanks for the quick fix. Now there is two times an assignment to the variable `data_files`. This line should be deleted:
https://github.com/janosh/matbench-discovery/blob/ee5b16188cec5de0f76dd9023d16dcb109eb246e/models/cgcnn/train_cgcnn.py#L64

**Comment by janosh** [comment]
Thanks!
