### ISSUE TITLE
Pytorch module and virtual environment usage

### ISSUE THREAD

**Issue by chiang-yuan** [janosh/matbench-discovery#53]
https://github.com/janosh/matbench-discovery/blob/7d80413d9b96771873cdbba7d404201ae975f481/models/mace/train_mace.py#L14

If I remembered correctly, once pytorch module on Perlmutter is loaded, all packaged will be installed by the `pip` provided by Perlmutter's pytorch module, not by the virtual env. That's to say, all the packages will be installed in module's conda environment in `$PYTHONUSERBASE` to be accessed correctly. ([NERSC Pytorch Doc](https://docs.nersc.gov/machinelearning/pytorch/#using-nersc-pytorch-modules)). 

If we force all the new packages to be installed in virtual env through **`pip` in virtual env**, some C kernel will not be found when we try to `import torch`

**Comment by janosh** [comment]
For long-term reproducibility, it would be preferable to install a specific release of the original MACE repo in case your fork is deleted or modified. Perhaps @ilyes319 can comment when the `multi-gpu` branch is expected to get merged. A new release after that would be much appreciated!

Regarding module loading `pytorch`, not sure I understand the problem. I didn't encounter any issues using the `slurm_submit` function in MBD and passing `pre_cmd="module load pytorch/2.0.1;", `.

https://github.com/janosh/matbench-discovery/blob/71d77f41242a566484321101f9ae6eb13e33ae66/models/alignn/train_alignn.py#L49-L57

**Comment by chiang-yuan** [comment]
There are a couple of differences between my `mbd` branch and `mace/multi-gpu`. I cloned `mace/multi-gpu` as `mbd` branch and merged `mace/gaussian` into `mace/multi-gpu`. 

Another word, `mace` has dependency on `pytorch` and whenever we try to install it in the virtualenv, it will install a new `pytorch` in the virtualenv and ignore the existing installation on Perlmutter's module. 

If we create a new `conda` env instead, we need to use the command `conda create --use-local` to correctly use Perlmutter's pytorch, but `mace` need to be installed in Perlmutter's conda env too. Installing mace in virtualenv will pass but will raise error when we try to use it.

**Comment by janosh** [comment]
I expect the `gaussian` and `multi-gpu` will both make their way into the next MACE release. The `gaussian` branch was [already merged into `develop`](https://github.com/ACEsuit/mace/pull/131).

I think the pytorch subtlety you mention is easily avoided by running `pip install git+https://github.com/ACEsuit/mace@develop --no-deps` which means `pip` will skip installing any dependencies and only install MACE itself. That's what I did for testing your MACE checkpoint.

**Comment by chiang-yuan** [comment]
You are right! That's what I used for the other conda environment. I used `conda create --user-local` and `pip install --no-deps` together. Somehow using `pip install --no-deps` in virtualenv didn't work for me. Maybe virtualenv has some integration problem with Perlmutter's module on my side.

I will change it to `--no-deps` and `develop` branch then. The conditional weight for forces may not be in `develop` but I think the difference is small.

**Comment by janosh** [comment]
I think we're good here? Feel free to re-open if not.

**Comment by chiang-yuan** [comment]
Yes all good. Just to keep a note here, we need to install pytorch-dependent packages all in one virtual environment. That means on Perlmutter MACE needs to be installed via pip provided by Perlmutter's pytorch module in order to use it directly without repeated installation. The other way is to install another pytorch and mace all together in a new virtual environment, in that case we don't need to `module load pytorch/2.0.1` on Perlmutter anymore.
