### ISSUE TITLE
dead link in contributing

### ISSUE THREAD

**Issue by bkmi** [janosh/matbench-discovery#55]
I'm interested in predicting ground truth energies. You mention a correction from MP20 and provide a link on this page.

> 11. e_form_per_atom_mp2020_corrected: Matbench Discovery takes these as ground truth for the formation energy. The result of applying the [MP2020 energy corrections](https://pymatgen.org/pymatgen.entries.compatibility.html#pymatgen.entries.compatibility.MaterialsProject2020Compatibility) (latest correction scheme at time of release) to e_form_per_atom_uncorrected.
> 12. e_correction_per_atom_mp2020: [MaterialsProject2020Compatibility](https://pymatgen.org/pymatgen.entries.compatibility.html#pymatgen.entries.compatibility.MaterialsProject2020Compatibility) energy corrections in eV/atom.
> 13. e_correction_per_atom_mp_legacy: Legacy [MaterialsProjectCompatibility](https://pymatgen.org/pymatgen.entries.compatibility.html#pymatgen.entries.compatibility.MaterialsProjectCompatibility) energy corrections in eV/atom. Having both old and new corrections allows updating predictions from older models like MEGNet that were trained on MP formation energies treated with the old correction scheme.

However, [that link](https://pymatgen.org/pymatgen.entries.compatibility.html) is a 404.

**Comment by janosh** [comment]
Thanks @bkmi for catching. Should be fixed.
