### ISSUE TITLE
Different training size for benchmarking

### ISSUE THREAD

**Issue by knc6** [janosh/matbench-discovery#68]
Hi,

I heard about this project at MRS Fall last week and I am looking at the matbench discovery page. Shouldn't training size (e.g. 1.6 million vs 133 k)  be the same for a fair comparison, else the model might be considered overfitting? This is machine learning 101.
![image](https://github.com/janosh/matbench-discovery/assets/16902896/1a83ca12-d6c2-44f8-baec-e9e4dc9018fd)

**Comment by janosh** [comment]
Also, training set size and overfitting are two different concepts which you seem to be conflating. What's more, the empirical evidence suggests overfitting is a non-issue with large models.
