### ISSUE TITLE
Inconsistency in GNoME's F1 Scores on Matbench

### ISSUE THREAD

**Issue by shrshr111** [janosh/matbench-discovery#91]
I noticed that the F1 scores for GNoME listed on two different web pages within the Matbench Discovery section appear to be inconsistent:

https://matbench-discovery.materialsproject.org/models
and
https://matbench-discovery.materialsproject.org/

Could someone please clarify why there is a difference in the reported F1 scores for GNoME? Thanks!

**Comment by janosh** [comment]
thanks for reporting! that is indeed a mistake. the model page was still showing metrics for the complete test set whereas the landing page recently transitioned to showing metrics on a subset of the WBM test set restricted to new and unique structures prototypes. see https://github.com/janosh/matbench-discovery/pull/75 for details.
